# Generated by Django 4.2.3 on 2023-07-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0006_remove_users_password_alter_users_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='address',
            new_name='add',
        ),
    ]
