# Generated by Django 4.2.3 on 2023-07-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0007_rename_address_users_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='add',
            field=models.CharField(max_length=2000),
        ),
    ]
