# Generated by Django 4.0.3 on 2023-07-06 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0008_alter_users_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_request',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users_request',
            name='state',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
