# Generated by Django 4.2.3 on 2023-07-06 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0009_users_dob_alter_users_request_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
