# Generated by Django 4.0.3 on 2023-07-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0009_alter_users_request_id_alter_users_request_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_request',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
