# Generated by Django 4.2.3 on 2023-07-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0010_alter_users_dob'),
        ('vmsApp', '0010_alter_users_request_id'),
    ]

    operations = [
    ]
